services:
  mineral_classifier:
    container_name: mineral_classifier_container
    image: my_mineral_classifier:latest
    build: .
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
    volumes:
      - .:/app
      - ./results:/app/results # Mount results directory
      - ./.dvc/cache:/app/.dvc/cache # Mount DVC cache to persist between runs
    # Default command (executed with docker-compose up)
    command: tail -f /dev/null # Keeps container running
    ports:
      - "8501:8501"
