services:
  mineral_classifier:
    container_name: mineral_classifier_container
    image: my_mineral_classifier:latest
    build: .
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
    volumes:
      - .:/app:rw
      - mineral_results:/app/results
      - dvc_cache:/app/.dvc/cache
    command: streamlit run app.py
    ports:
      - "8501:8501"

volumes:
  mineral_results:
    driver: local
  dvc_cache:
    driver: local