services:
  mineral_classifier:
    container_name: mineral_classifier_container
    image: my_mineral_classifier:latest
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "8501:8501"
    volumes:
      - mineral_results:/app/results
      - dvc_cache:/app/.dvc/cache
    restart: unless-stopped

volumes:
  mineral_results:
    driver: local
  dvc_cache:
    driver: local
