stages:
  bootstrap:
    cmd: python src/stages/generate_base_data.py --cycle 0
    deps:
    - src/stages/generate_base_data.py
    params:
    - data.base
    outs:
    - results/data/base/cycle_0
  cycle_1:
    cmd: python src/run_cycle.py --cycle 1 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_0
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_1
    - results/data/prediction/cycle_1
    - results/trained/cycle_1
    - results/evaluation/cycle_1
    - results/drift_analysis/cycle_1
  cycle_2:
    cmd: python src/run_cycle.py --cycle 2 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_1
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_2
    - results/data/prediction/cycle_2
    - results/trained/cycle_2
    - results/evaluation/cycle_2
    - results/drift_analysis/cycle_2
  cycle_3:
    cmd: python src/run_cycle.py --cycle 3 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_2
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_3
    - results/data/prediction/cycle_3
    - results/trained/cycle_3
    - results/evaluation/cycle_3
    - results/drift_analysis/cycle_3
  cycle_4:
    cmd: python src/run_cycle.py --cycle 4 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_3
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_4
    - results/data/prediction/cycle_4
    - results/trained/cycle_4
    - results/evaluation/cycle_4
    - results/drift_analysis/cycle_4
  cycle_5:
    cmd: python src/run_cycle.py --cycle 5 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_4
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_5
    - results/data/prediction/cycle_5
    - results/trained/cycle_5
    - results/evaluation/cycle_5
    - results/drift_analysis/cycle_5
  cycle_6:
    cmd: python src/run_cycle.py --cycle 6 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_5
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_6
    - results/data/prediction/cycle_6
    - results/trained/cycle_6
    - results/evaluation/cycle_6
    - results/drift_analysis/cycle_6
  cycle_7:
    cmd: python src/run_cycle.py --cycle 7 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_6
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_7
    - results/data/prediction/cycle_7
    - results/trained/cycle_7
    - results/evaluation/cycle_7
    - results/drift_analysis/cycle_7
  cycle_8:
    cmd: python src/run_cycle.py --cycle 8 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_7
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_8
    - results/data/prediction/cycle_8
    - results/trained/cycle_8
    - results/evaluation/cycle_8
    - results/drift_analysis/cycle_8
  cycle_9:
    cmd: python src/run_cycle.py --cycle 9 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_8
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_9
    - results/data/prediction/cycle_9
    - results/trained/cycle_9
    - results/evaluation/cycle_9
    - results/drift_analysis/cycle_9
  cycle_10:
    cmd: python src/run_cycle.py --cycle 10 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_9
    params:
    - models.gat
    - data
    - train
    - evaluate
    outs:
    - results/data/base/cycle_10
    - results/data/prediction/cycle_10
    - results/trained/cycle_10
    - results/evaluation/cycle_10
    - results/drift_analysis/cycle_10
