stages:
  generate_data:
    cmd: python src/stages/generate_synthetic_data.py
    deps:
      - src/stages/generate_synthetic_data.py
      - src/utilities/data_utils.py
    params:
      - data
    outs:
      - results/data
  train:
    cmd: python src/stages/train.py --model ${model}
    deps:
      - src/stages/train.py
      - src/models/
      - src/utilities/logging_utils.py
      - src/utilities/train_utils.py
      - results/data
    params:
      - model
      - models.${model}
      - train
    outs:
      - results/trained
  evaluate:
    cmd: python src/stages/evaluate.py --model ${model}
    deps:
      - src/stages/evaluate.py
      - src/models/
      - src/utilities/logging_utils.py
      - src/utilities/calibration_utils.py
      - src/utilities/eval_utils.py
      - results/trained
    params:
      - evaluate
    outs:
      - results/evaluation
  predict:
      cmd: python src/stages/predict.py --model ${model}
      deps:
        - src/stages/predict.py
        - src/models/
        - src/utilities/logging_utils.py
        - src/utilities/calibration_utils.py
        - src/utilities/pred_utils.py
        - results/data
        - results/evaluation
