stages:
  bootstrap:
    cmd: python src/stages/generate_base_data.py --cycle 0
    deps:
    - src/stages/generate_base_data.py
    params:
    - data.base
    outs:
    - results/data/base/cycle_0
  cycle_1:
    cmd: python src/run_cycle.py --cycle 1 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_0
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_1
    - results/data/prediction/cycle_1
    - results/trained/cycle_1
    - results/evaluation/cycle_1
    - results/drift_analysis/cycle_1
  cycle_2:
    cmd: python src/run_cycle.py --cycle 2 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_1
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_2
    - results/data/prediction/cycle_2
    - results/trained/cycle_2
    - results/evaluation/cycle_2
    - results/drift_analysis/cycle_2
  cycle_3:
    cmd: python src/run_cycle.py --cycle 3 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_2
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_3
    - results/data/prediction/cycle_3
    - results/trained/cycle_3
    - results/evaluation/cycle_3
    - results/drift_analysis/cycle_3
  cycle_4:
    cmd: python src/run_cycle.py --cycle 4 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_3
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_4
    - results/data/prediction/cycle_4
    - results/trained/cycle_4
    - results/evaluation/cycle_4
    - results/drift_analysis/cycle_4
  cycle_5:
    cmd: python src/run_cycle.py --cycle 5 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_4
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_5
    - results/data/prediction/cycle_5
    - results/trained/cycle_5
    - results/evaluation/cycle_5
    - results/drift_analysis/cycle_5
  cycle_6:
    cmd: python src/run_cycle.py --cycle 6 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_5
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_6
    - results/data/prediction/cycle_6
    - results/trained/cycle_6
    - results/evaluation/cycle_6
    - results/drift_analysis/cycle_6
  cycle_7:
    cmd: python src/run_cycle.py --cycle 7 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_6
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_7
    - results/data/prediction/cycle_7
    - results/trained/cycle_7
    - results/evaluation/cycle_7
    - results/drift_analysis/cycle_7
  cycle_8:
    cmd: python src/run_cycle.py --cycle 8 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_7
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_8
    - results/data/prediction/cycle_8
    - results/trained/cycle_8
    - results/evaluation/cycle_8
    - results/drift_analysis/cycle_8
  cycle_9:
    cmd: python src/run_cycle.py --cycle 9 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_8
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_9
    - results/data/prediction/cycle_9
    - results/trained/cycle_9
    - results/evaluation/cycle_9
    - results/drift_analysis/cycle_9
  cycle_10:
    cmd: python src/run_cycle.py --cycle 10 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_9
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_10
    - results/data/prediction/cycle_10
    - results/trained/cycle_10
    - results/evaluation/cycle_10
    - results/drift_analysis/cycle_10
  cycle_11:
    cmd: python src/run_cycle.py --cycle 11 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_10
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_11
    - results/data/prediction/cycle_11
    - results/trained/cycle_11
    - results/evaluation/cycle_11
    - results/drift_analysis/cycle_11
  cycle_12:
    cmd: python src/run_cycle.py --cycle 12 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_11
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_12
    - results/data/prediction/cycle_12
    - results/trained/cycle_12
    - results/evaluation/cycle_12
    - results/drift_analysis/cycle_12
  cycle_13:
    cmd: python src/run_cycle.py --cycle 13 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_12
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_13
    - results/data/prediction/cycle_13
    - results/trained/cycle_13
    - results/evaluation/cycle_13
    - results/drift_analysis/cycle_13
  cycle_14:
    cmd: python src/run_cycle.py --cycle 14 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_13
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_14
    - results/data/prediction/cycle_14
    - results/trained/cycle_14
    - results/evaluation/cycle_14
    - results/drift_analysis/cycle_14
  cycle_15:
    cmd: python src/run_cycle.py --cycle 15 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_14
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_15
    - results/data/prediction/cycle_15
    - results/trained/cycle_15
    - results/evaluation/cycle_15
    - results/drift_analysis/cycle_15
  cycle_16:
    cmd: python src/run_cycle.py --cycle 16 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_15
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_16
    - results/data/prediction/cycle_16
    - results/trained/cycle_16
    - results/evaluation/cycle_16
    - results/drift_analysis/cycle_16
  cycle_17:
    cmd: python src/run_cycle.py --cycle 17 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_16
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_17
    - results/data/prediction/cycle_17
    - results/trained/cycle_17
    - results/evaluation/cycle_17
    - results/drift_analysis/cycle_17
  cycle_18:
    cmd: python src/run_cycle.py --cycle 18 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_17
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_18
    - results/data/prediction/cycle_18
    - results/trained/cycle_18
    - results/evaluation/cycle_18
    - results/drift_analysis/cycle_18
  cycle_19:
    cmd: python src/run_cycle.py --cycle 19 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_18
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_19
    - results/data/prediction/cycle_19
    - results/trained/cycle_19
    - results/evaluation/cycle_19
    - results/drift_analysis/cycle_19
  cycle_20:
    cmd: python src/run_cycle.py --cycle 20 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_19
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_20
    - results/data/prediction/cycle_20
    - results/trained/cycle_20
    - results/evaluation/cycle_20
    - results/drift_analysis/cycle_20
  cycle_21:
    cmd: python src/run_cycle.py --cycle 21 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_20
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_21
    - results/data/prediction/cycle_21
    - results/trained/cycle_21
    - results/evaluation/cycle_21
    - results/drift_analysis/cycle_21
  cycle_22:
    cmd: python src/run_cycle.py --cycle 22 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_21
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_22
    - results/data/prediction/cycle_22
    - results/trained/cycle_22
    - results/evaluation/cycle_22
    - results/drift_analysis/cycle_22
  cycle_23:
    cmd: python src/run_cycle.py --cycle 23 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_22
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_23
    - results/data/prediction/cycle_23
    - results/trained/cycle_23
    - results/evaluation/cycle_23
    - results/drift_analysis/cycle_23
  cycle_24:
    cmd: python src/run_cycle.py --cycle 24 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_23
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_24
    - results/data/prediction/cycle_24
    - results/trained/cycle_24
    - results/evaluation/cycle_24
    - results/drift_analysis/cycle_24
  cycle_25:
    cmd: python src/run_cycle.py --cycle 25 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_24
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_25
    - results/data/prediction/cycle_25
    - results/trained/cycle_25
    - results/evaluation/cycle_25
    - results/drift_analysis/cycle_25
  cycle_26:
    cmd: python src/run_cycle.py --cycle 26 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_25
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_26
    - results/data/prediction/cycle_26
    - results/trained/cycle_26
    - results/evaluation/cycle_26
    - results/drift_analysis/cycle_26
  cycle_27:
    cmd: python src/run_cycle.py --cycle 27 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_26
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_27
    - results/data/prediction/cycle_27
    - results/trained/cycle_27
    - results/evaluation/cycle_27
    - results/drift_analysis/cycle_27
  cycle_28:
    cmd: python src/run_cycle.py --cycle 28 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_27
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_28
    - results/data/prediction/cycle_28
    - results/trained/cycle_28
    - results/evaluation/cycle_28
    - results/drift_analysis/cycle_28
  cycle_29:
    cmd: python src/run_cycle.py --cycle 29 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_28
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_29
    - results/data/prediction/cycle_29
    - results/trained/cycle_29
    - results/evaluation/cycle_29
    - results/drift_analysis/cycle_29
  cycle_30:
    cmd: python src/run_cycle.py --cycle 30 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_29
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_30
    - results/data/prediction/cycle_30
    - results/trained/cycle_30
    - results/evaluation/cycle_30
    - results/drift_analysis/cycle_30
  analyze_performance:
    cmd: python src/stages/analyze_cycle_performance.py
    deps:
    - src/stages/analyze_cycle_performance.py
    - results/evaluation/cycle_1/metrics.json
    - results/prediction/cycle_1/metrics.json
    - results/evaluation/cycle_2/metrics.json
    - results/prediction/cycle_2/metrics.json
    - results/evaluation/cycle_3/metrics.json
    - results/prediction/cycle_3/metrics.json
    - results/evaluation/cycle_4/metrics.json
    - results/prediction/cycle_4/metrics.json
    - results/evaluation/cycle_5/metrics.json
    - results/prediction/cycle_5/metrics.json
    - results/evaluation/cycle_6/metrics.json
    - results/prediction/cycle_6/metrics.json
    - results/evaluation/cycle_7/metrics.json
    - results/prediction/cycle_7/metrics.json
    - results/evaluation/cycle_8/metrics.json
    - results/prediction/cycle_8/metrics.json
    - results/evaluation/cycle_9/metrics.json
    - results/prediction/cycle_9/metrics.json
    - results/evaluation/cycle_10/metrics.json
    - results/prediction/cycle_10/metrics.json
    - results/evaluation/cycle_11/metrics.json
    - results/prediction/cycle_11/metrics.json
    - results/evaluation/cycle_12/metrics.json
    - results/prediction/cycle_12/metrics.json
    - results/evaluation/cycle_13/metrics.json
    - results/prediction/cycle_13/metrics.json
    - results/evaluation/cycle_14/metrics.json
    - results/prediction/cycle_14/metrics.json
    - results/evaluation/cycle_15/metrics.json
    - results/prediction/cycle_15/metrics.json
    - results/evaluation/cycle_16/metrics.json
    - results/prediction/cycle_16/metrics.json
    - results/evaluation/cycle_17/metrics.json
    - results/prediction/cycle_17/metrics.json
    - results/evaluation/cycle_18/metrics.json
    - results/prediction/cycle_18/metrics.json
    - results/evaluation/cycle_19/metrics.json
    - results/prediction/cycle_19/metrics.json
    - results/evaluation/cycle_20/metrics.json
    - results/prediction/cycle_20/metrics.json
    - results/evaluation/cycle_21/metrics.json
    - results/prediction/cycle_21/metrics.json
    - results/evaluation/cycle_22/metrics.json
    - results/prediction/cycle_22/metrics.json
    - results/evaluation/cycle_23/metrics.json
    - results/prediction/cycle_23/metrics.json
    - results/evaluation/cycle_24/metrics.json
    - results/prediction/cycle_24/metrics.json
    - results/evaluation/cycle_25/metrics.json
    - results/prediction/cycle_25/metrics.json
    - results/evaluation/cycle_26/metrics.json
    - results/prediction/cycle_26/metrics.json
    - results/evaluation/cycle_27/metrics.json
    - results/prediction/cycle_27/metrics.json
    - results/evaluation/cycle_28/metrics.json
    - results/prediction/cycle_28/metrics.json
    - results/evaluation/cycle_29/metrics.json
    - results/prediction/cycle_29/metrics.json
    - results/evaluation/cycle_30/metrics.json
    - results/prediction/cycle_30/metrics.json
    outs:
    - results/performance_analysis/cycle_performance.png
