stages:
  bootstrap:
    cmd: python src/stages/generate_base_data.py --cycle 0
    deps:
    - src/stages/generate_base_data.py
    params:
    - data.base
    outs:
    - results/data/base/cycle_0
  cycle_1:
    cmd: python src/run_cycle.py --cycle 1 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_0
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_1
    - results/data/prediction/cycle_1
    - results/trained/cycle_1
    - results/evaluation/cycle_1
    - results/drift_analysis/cycle_1
  cycle_2:
    cmd: python src/run_cycle.py --cycle 2 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_1
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_2
    - results/data/prediction/cycle_2
    - results/trained/cycle_2
    - results/evaluation/cycle_2
    - results/drift_analysis/cycle_2
  cycle_3:
    cmd: python src/run_cycle.py --cycle 3 --model gat
    deps:
    - src/run_cycle.py
    - src/stages/
    - src/models/
    - src/utilities/
    - results/data/base/cycle_2
    params:
    - models.gat
    - data
    - train
    - evaluate
    - analyze_drift
    outs:
    - results/data/base/cycle_3
    - results/data/prediction/cycle_3
    - results/trained/cycle_3
    - results/evaluation/cycle_3
    - results/drift_analysis/cycle_3
  analyze_performance:
    cmd: python src/stages/analyze_cycle_performance.py
    deps:
    - src/stages/analyze_cycle_performance.py
    - results/evaluation/cycle_1/metrics.json
    - results/prediction/cycle_1/metrics.json
    - results/evaluation/cycle_2/metrics.json
    - results/prediction/cycle_2/metrics.json
    - results/evaluation/cycle_3/metrics.json
    - results/prediction/cycle_3/metrics.json
    outs:
    - results/performance_analysis/cycle_performance.png
