# Training cycle configuration
cycles: "1-30"
default_model: gat

# Data generation parameters
data:
  base:
    radius: 2500
    depth: -500
    n_samples: 1000
    spacing: 10
    n_features: 5
    n_classes: 2
    threshold_binary: 0.5
    min_samples_per_class: 20
    connection_radius: 100
    add_self_loops: true
    n_splits: 2
    test_size: 0.3
    calib_size: 0.50
    n_hotspots: 5
    n_hotspots_random: false
    seed: 2321
  pred:
    n_samples: 200
    min_samples_per_class:
    seed:

# Model parameters
models:
  gat:
    hidden_channels: 64
    n_layers: 3
    n_heads: 5
    dropout: 0.3
    batch_norm: true
    negative_slope: 0.2
    add_self_loops: true
    bias: true
    residual: false
  gcn:
    hidden_channels: 64
    n_layers: 3
    dropout: 0.3
    batch_norm: true
    improved: false
    add_self_loops: true
    normalize: true

# Training parameters
train:
  n_epochs: 1000
  lr: 0.001
  max_grad_norm: 1.0
  weight_decay_adam_optimizer: 5.0e-4
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1.0e-3
  strategy: "from_scratch"  # "incremental" or "from_scratch"
  warmup_epochs: 50       # Gradual LR increase for new data
  freeze_early_layers: true  # Freeze first layer for stability

# Evaluation parameters
evaluate:
  initial_temperature: 1.2
  n_bins: 10
  class_names:
  calibration_method: beta
  n_epochs: 1000
  lr: 1.0e-3
  weight_decay_adam_optimizer: 5.0e-4
  verbose: true
  factor_learning_rate_scheduler: 0.4
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 100
  min_delta_early_stopping: 1.0e-3
  reg_lambda: 1.0e-2
  reg_mu: 1.0e-2
  eps: 1.0e-8
  seed: 40

# Drift detection parameters
analyze_drift:
  n_permutations: 1000
  use_max_sliced_wasserstein:
  n_projections: 100
  use_sinkhorn_wasserstein:
  sinkhorn_wasserstein_reg: 0.1
  gamma:
  early_stopping:
    enabled: true
    confidence_threshold: 0.01  # Stop early if p-value < threshold
    min_permutations: 100  # Minimum permutations before early stopping