data:
  n_samples: 1000
  spacing: 50
  depth: -500
  n_features: 4
  n_classes: 5
  threshold_binary: 0.5
  min_samples_per_class: 15
  connection_radius: 150
  n_splits: 5
  test_size: 0.3
  calib_size: 0.50
  seed: 10

# Default model selection
model: gcn
# Model parameters
models:
  gat:
    hidden_channels: 64
    n_layers: 3
    n_heads: 5
    dropout: 0.3
    batch_norm: true
  gcn:
    hidden_channels: 64
    n_layers: 3
    dropout: 0.3
    batch_norm: true

# Training parameters
train:
  n_epochs: 1000
  lr: 0.001
  max_grad_norm: 1.0
  weight_decay_adam_optimizer: 5.0e-4
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1.0e-3
  seed: 40

# Evaluation parameters
evaluate:
  initial_temperature: 0.9
  n_bins: 10
  class_names:
  - low
  - medium-low
  - medium
  - medium-high
  - high
  calibration_method: dirichlet
  n_epochs: 1000
  lr: 1.0e-3
  weight_decay_adam_optimizer: 5.0e-4
  verbose: true
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1.0e-3
  reg_lambda: 1.0e-2
  reg_mu: 1.0e-2
  eps: 1.0e-8
  seed: 40
