# Training cycle configuration
cycles: 1
add_self_loops: true
default_model: gcn

# Data generation parameters
data:
  scaler_type: RobustScaler # Options: RobustScaler, StandardScaler, MinMaxScaler
  scaler_params:
    quantile_range:
    - 25.0
    - 75.0
  make_edge_weight: true
  make_edge_weight_method: minmax    # Options: minmax, standard, softmax, log, None
  base:
    radius: 2500
    depth: -500
    n_samples: 1000
    spacing: 10
    n_features: 5
    n_classes: 5
    class_names:
    threshold_binary: 0.5
    min_samples_per_class: 50
    connection_radius: 500
    n_splits: 3
    test_size: 0.3
    calib_size: 0.50
    n_hotspots: 5
    n_hotspots_random: false
    seed: 546110
  pred:
    n_samples: 200
    min_samples_per_class:
    seed:

# Model parameters
models:
  gat:
    hidden_channels: 64
    n_layers: 3
    n_heads: 5
    dropout: 0.1
    batch_norm: true
    negative_slope: 0.2
    bias: true
    residual: true
  gcn:
    hidden_channels: 128
    n_layers: 3
    dropout: 0.4
    batch_norm: true
    improved: true
    normalize: true

# Training parameters
train:
  n_epochs: 1000
  lr: 0.001
  max_grad_norm: 1.0
  weight_decay_adam_optimizer: 5.0e-4
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1.0e-3

# Evaluation parameters
evaluate:
  initial_temperature: 1.2
  n_bins: 10
  calibration_method: beta # Options: "temperature", "isotonic", "platt", "beta", "dirichlet"
  n_epochs: 1000
  lr: 1.0e-3
  weight_decay_adam_optimizer: 5.0e-4
  verbose: true
  factor_learning_rate_scheduler: 0.4
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 100
  min_delta_early_stopping: 1.0e-3
  reg_lambda: 1.0e-2
  reg_mu: 1.0e-2
  eps: 1.0e-8
  seed: 40

# Drift detection parameters
analyze_drift:
  n_permutations: 1000
  use_max_sliced_wasserstein:
  n_projections: 100
  use_sinkhorn_wasserstein:
  sinkhorn_wasserstein_reg: 0.1
  gamma:
  early_stopping:
    enabled: true
    confidence_threshold: 0.01  # Stop early if p-value < threshold
    min_permutations: 100  # Minimum permutations before early stopping
