[project]
name = "mineral-classifier"
version = "0.1.0"
description = "Machine learning project for mineral classification"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "POT>=0.9.5",
    "dvc>=3.56, <4.0",
    "pathspec>=0.12",
    "plotly>=5.24.1",
    "ruamel.yaml>=0.18.15",
    "scikit-learn>=1.6.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.4",
    "streamlit>=1.45.1",
    "torch>=2.6.0",
    "torch-geometric>=2.6.1",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.5",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

# ---- Pytest ----
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

# ---- Ruff ----
[tool.ruff]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]
line-length = 88
indent-width = 4
target-version = "py311"
show-fixes = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 60

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "PD",  # pandas-vet
  "NPY",  # numpy-specific
  "RUF",  # ruff-specific
  "D",  # pydocstyle
  "SIM",  # flake8-simplify
]
ignore = ["E501", "B008", "C901"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.uv.sources]
torch = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
