data:
  origin: [657161, 688292, 0]
  x_spacing: 2.5
  y_spacing: 2.5
  z_spacing: 2.5
  x_length: 50
  y_length: 50
  z_depth: 40
  n_features: 4
  n_classes: 5
  d_threshold: 5
  edge_dim: 2
  n_splits: 5
  test_size: 0.3
  calib_size: 0.50
  seed: 40

# Default model selection
model: "gat"
# Model parameters
models:
  gat:
    hidden_channels: 64
    n_layers: 3
    n_heads: 5
    dropout: 0.3
    batch_norm: True
  gcn:
    hidden_channels: 64
    n_layers: 3
    dropout: 0.3
    batch_norm: True

# Training parameters
train:
  n_epochs: 1000
  lr: 1e-3
  max_grad_norm: 1.0
  weight_decay_adam_optimizer: 5e-4
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1e-3
  seed: 40

# Evaluation parameters
evaluate:
  initial_temperature: 1.1
  n_bins: 10
  class_names: ["low", "medium-low", "medium", "medium-high", "high"]
  calibration_method: "temperature"
  n_epochs: 1000
  lr: 1e-3
  weight_decay_adam_optimizer: 5e-4
  verbose: True
  factor_learning_rate_scheduler: 0.5
  patience_learning_rate_scheduler: 20
  patience_early_stopping: 50
  min_delta_early_stopping: 1e-3
